version : "3"
services:
  keycloak:
    image: jboss/keycloak:7.0.1
    container_name: keycloak
    restart: always
    ports:
      - 8180:8180
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    volumes:
      - ./ng-keycloak-sample-realm.json:/config/ng-keycloak-sample-realm.json
    command: >
      -b 0.0.0.0
      -Djboss.http.port=8180
      -Dkeycloak.migration.action=import
      -Dkeycloak.migration.provider=singleFile
      -Dkeycloak.migration.file=/config/ng-keycloak-sample-realm.json
      -Dkeycloak.migration.strategy=OVERWRITE_EXISTING
    tty: true
